# Generated by Django 5.0.1 on 2024-01-25 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autopark', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carbrand',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='cartype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='parkingslot',
            options={'ordering': ['number']},
        ),
        migrations.RemoveField(
            model_name='parking',
            name='parking_slots',
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='parking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autopark.parking'),
        ),
    ]
